/*
Date: 12/09/2022
Authot: Erique Abel Herrera Vargas
Email: up210894@alumnos.upa.edu.mx
Description: Mi primer porgrama en C++
*/

//-----------PREPROCESSOR DIRECTIVES----------
// Input/Output LIbrary between the screet "n" keyboard
#include <iostream>
//-----------MAIN FUNTION---------
int main()
{
    // Prints on screen a text
    std::cout << "Hi world" << std::endl;
    // Return 0 means that teh program ends succesfully
    return 0;
}
